/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QaRouteImport } from './routes/qa'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as CompanyPausedRouteImport } from './routes/company-paused'
import { Route as AwaitingRoleRouteImport } from './routes/awaiting-role'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as QaRejectedRouteImport } from './routes/qa.rejected'
import { Route as QaPendingRouteImport } from './routes/qa.pending'
import { Route as QaApprovedRouteImport } from './routes/qa.approved'
import { Route as ProductionNewrequestRouteImport } from './routes/production.newrequest'
import { Route as ProductionHistoryRouteImport } from './routes/production.history'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSignaturesRouteImport } from './routes/admin.signatures'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPausedRoute = CompanyPausedRouteImport.update({
  id: '/company-paused',
  path: '/company-paused',
  getParentRoute: () => rootRouteImport,
} as any)
const AwaitingRoleRoute = AwaitingRoleRouteImport.update({
  id: '/awaiting-role',
  path: '/awaiting-role',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const QaRejectedRoute = QaRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => QaRoute,
} as any)
const QaPendingRoute = QaPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => QaRoute,
} as any)
const QaApprovedRoute = QaApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => QaRoute,
} as any)
const ProductionNewrequestRoute = ProductionNewrequestRouteImport.update({
  id: '/newrequest',
  path: '/newrequest',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionHistoryRoute = ProductionHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProductionRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignaturesRoute = AdminSignaturesRouteImport.update({
  id: '/signatures',
  path: '/signatures',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awaiting-role': typeof AwaitingRoleRoute
  '/company-paused': typeof CompanyPausedRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRouteWithChildren
  '/qa': typeof QaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/signatures': typeof AdminSignaturesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/production/history': typeof ProductionHistoryRoute
  '/production/newrequest': typeof ProductionNewrequestRoute
  '/qa/approved': typeof QaApprovedRoute
  '/qa/pending': typeof QaPendingRoute
  '/qa/rejected': typeof QaRejectedRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awaiting-role': typeof AwaitingRoleRoute
  '/company-paused': typeof CompanyPausedRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRouteWithChildren
  '/qa': typeof QaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/signatures': typeof AdminSignaturesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/production/history': typeof ProductionHistoryRoute
  '/production/newrequest': typeof ProductionNewrequestRoute
  '/qa/approved': typeof QaApprovedRoute
  '/qa/pending': typeof QaPendingRoute
  '/qa/rejected': typeof QaRejectedRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awaiting-role': typeof AwaitingRoleRoute
  '/company-paused': typeof CompanyPausedRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRouteWithChildren
  '/qa': typeof QaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/signatures': typeof AdminSignaturesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/production/history': typeof ProductionHistoryRoute
  '/production/newrequest': typeof ProductionNewrequestRoute
  '/qa/approved': typeof QaApprovedRoute
  '/qa/pending': typeof QaPendingRoute
  '/qa/rejected': typeof QaRejectedRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/awaiting-role'
    | '/company-paused'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/production'
    | '/qa'
    | '/reset-password'
    | '/signup'
    | '/super-admin'
    | '/admin/signatures'
    | '/admin/teams'
    | '/admin/templates'
    | '/production/history'
    | '/production/newrequest'
    | '/qa/approved'
    | '/qa/pending'
    | '/qa/rejected'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/awaiting-role'
    | '/company-paused'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/production'
    | '/qa'
    | '/reset-password'
    | '/signup'
    | '/admin/signatures'
    | '/admin/teams'
    | '/admin/templates'
    | '/production/history'
    | '/production/newrequest'
    | '/qa/approved'
    | '/qa/pending'
    | '/qa/rejected'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/awaiting-role'
    | '/company-paused'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/production'
    | '/qa'
    | '/reset-password'
    | '/signup'
    | '/super-admin'
    | '/admin/signatures'
    | '/admin/teams'
    | '/admin/templates'
    | '/production/history'
    | '/production/newrequest'
    | '/qa/approved'
    | '/qa/pending'
    | '/qa/rejected'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AwaitingRoleRoute: typeof AwaitingRoleRoute
  CompanyPausedRoute: typeof CompanyPausedRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProductionRoute: typeof ProductionRouteWithChildren
  QaRoute: typeof QaRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-paused': {
      id: '/company-paused'
      path: '/company-paused'
      fullPath: '/company-paused'
      preLoaderRoute: typeof CompanyPausedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awaiting-role': {
      id: '/awaiting-role'
      path: '/awaiting-role'
      fullPath: '/awaiting-role'
      preLoaderRoute: typeof AwaitingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/qa/rejected': {
      id: '/qa/rejected'
      path: '/rejected'
      fullPath: '/qa/rejected'
      preLoaderRoute: typeof QaRejectedRouteImport
      parentRoute: typeof QaRoute
    }
    '/qa/pending': {
      id: '/qa/pending'
      path: '/pending'
      fullPath: '/qa/pending'
      preLoaderRoute: typeof QaPendingRouteImport
      parentRoute: typeof QaRoute
    }
    '/qa/approved': {
      id: '/qa/approved'
      path: '/approved'
      fullPath: '/qa/approved'
      preLoaderRoute: typeof QaApprovedRouteImport
      parentRoute: typeof QaRoute
    }
    '/production/newrequest': {
      id: '/production/newrequest'
      path: '/newrequest'
      fullPath: '/production/newrequest'
      preLoaderRoute: typeof ProductionNewrequestRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/history': {
      id: '/production/history'
      path: '/history'
      fullPath: '/production/history'
      preLoaderRoute: typeof ProductionHistoryRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signatures': {
      id: '/admin/signatures'
      path: '/signatures'
      fullPath: '/admin/signatures'
      preLoaderRoute: typeof AdminSignaturesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSignaturesRoute: typeof AdminSignaturesRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSignaturesRoute: AdminSignaturesRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductionRouteChildren {
  ProductionHistoryRoute: typeof ProductionHistoryRoute
  ProductionNewrequestRoute: typeof ProductionNewrequestRoute
}

const ProductionRouteChildren: ProductionRouteChildren = {
  ProductionHistoryRoute: ProductionHistoryRoute,
  ProductionNewrequestRoute: ProductionNewrequestRoute,
}

const ProductionRouteWithChildren = ProductionRoute._addFileChildren(
  ProductionRouteChildren,
)

interface QaRouteChildren {
  QaApprovedRoute: typeof QaApprovedRoute
  QaPendingRoute: typeof QaPendingRoute
  QaRejectedRoute: typeof QaRejectedRoute
}

const QaRouteChildren: QaRouteChildren = {
  QaApprovedRoute: QaApprovedRoute,
  QaPendingRoute: QaPendingRoute,
  QaRejectedRoute: QaRejectedRoute,
}

const QaRouteWithChildren = QaRoute._addFileChildren(QaRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AwaitingRoleRoute: AwaitingRoleRoute,
  CompanyPausedRoute: CompanyPausedRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProductionRoute: ProductionRouteWithChildren,
  QaRoute: QaRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
